### ISSUE TITLE
permission code

### ISSUE THREAD

**Issue by chrisvidal** [joakimbo/user-permissions-plugin#2]
It would be interesting to use permission code so the functions would be

```
{% if user.hasUserPermission(permissionCode) %}
```

so we can change the permission name any time without impacting the rest of the code.

**Comment by joakimbo** [comment]
Hi Chris,
Is what you want to achieve not possible with the existing `hasUserPermissionWithId()` function?

**Comment by chrisvidal** [comment]
The id is not really human readable. A code/slug would be.

**Comment by joakimbo** [comment]
I understand the predicament but I fail to see how adding a code/slug column would be necessary. Why not treat the permission name as the human readable part? Perhaps you could provide an example that illustrates this need?

**Comment by pvullioud** [comment]
+1 for a slug like in the group of Rainlab.User
https://monosnap.com/file/TGitiiQ0tcnmVVuVXYUjOmd0VnLo0F

**Comment by chrisvidal** [comment]
a Label / name can change but a slug is an internal code that won't change hence the code will be bug proof after any change.

**Comment by joakimbo** [comment]
Hi @chrisvidal and @pvullioud I have now updated this plugin to include a code field for permissions along with various other changes and will therefore close this issue.
