### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by ovillani** [joakimbo/user-permissions-plugin#6]
Using MariaDb I cannot save a new usergroup.
Error message is:

"SQLSTATE[HY000]: General error: 1364 Field 'permission_state' doesn't have a default value (SQL: insert into `jbonnydev_userpermissions_group_permission` (`created_at`, `group_id`, `permission_id`, `updated_at`) values (2020-10-13 11:03:35, 5, 1, 2020-10-13 11:03:35))" on line 664 of /home/.../vendor/laravel/framework/src/Illuminate/Database/Connection.php

Installed the Doctrine plugin to fix this problem, did not help either!

Edit: It's NOT because of the timestamps (was my first guess without noticing the message detail), it's because of a missed 'permission_state'.

**Comment by joakimbo** [comment]
Hi @ovillani , thank you for your issue report. 

I have pushed a fix for this as of today which should hopefully solve the described issue. Could you
possibly test the latest version and report back if the issue has been resolved?

**Comment by ovillani** [comment]
Hello joakimbo,
tested it just now, is working without any problems on MariaDB!
Thanks a lot :)

**Comment by joakimbo** [comment]
Hello again @ovillani

Thats good to hear :) I will consider this issue resolved.
