### ISSUE TITLE
Add composer.json + questions

### ISSUE THREAD

**Issue by RomainMazB** [joakimbo/user-permissions-plugin#7]
Hi @joakimbo,

I'd like to use your plugin as a required of one I'm currently building, but I have some few questions:

Could it be possible to publish the package on packagist? The plugin I want to use it is actually for another platform (WinterCMS) and I'd love to use composer.json to include your plugin into mine.
Also OctoberCMS 2.0 only support plugins updates through composer.

I see in the code that you have created a custom formwidget which reproduce the exact same behavior/appearance of the core's [`PermissionEditor` formwidget](https://octobercms.com/docs/api/backend/formwidgets/permissioneditor). Is there a good reason to do that? Did you try to extend it but faced blocking problem?

Also I see that you've used condition to insert or not the sidemenu link to the Users controller, why didn't you use the basic [`permission` key](https://octobercms.com/docs/plugin/registration#navigation-menus) on the menu?

If you are interested in those changes, I could do some separated PR to implement them individually.

**Comment by joakimbo** [comment]
Hi @RomainMazB, and thank you for your interest in this plugin.

Regarding publishing this plugin on packagist, this is not something I am interested in and its reasons are more or less answers to your other questions. The codebase for this plugin was written in 2019 and I'm sorry to say that I do not remember what the best practices were back then nor do I know what they are today regarding plugins for OctoberCMS, nor do I remember specifics about what issues I might have encountered during the development of this plugin.
For me to approve any pull requests I would need to get up to date about these thing which is unfortunately not something I currently have the time to do. I will point out however that the code is licensed under MIT so you are free to fork and/or copy this code to distribute and improve upon any way you like as long as you adhere to the license.

I apologize for not being of more use but I wish you the best with your endeavours.

/ joakimbo

**Comment by RomainMazB** [comment]
@joakimbo, thanks for the rapid answer.

That's not a problem, I'll just look at the codebase to inspire myself to reproduce what I need.
